# Generated by Django 4.2.2 on 2024-02-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erental_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='bank_acc_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
